### ISSUE TITLE
Meta: Standardize issue workflow on solid/solid 

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/solid-spec#75]
Currently, the Issues section of this repo (`solid-spec`) is being used as a central place to bring up questions about the Solid platform, and to track feature requests across various Solid servers and libraries. (Examples: #68, #67, #69, #73, etc).

As a result of discussion with @deiu, we're instead going to standardize on the [solid/solid](https://github.com/solid) repo for these issues. 

So, the default workflow will be as follows:

1. Have a question or a feature request or a concern about the Solid framework, or on one of its servers? **Open an issue on [solid/solid](https://github.com/solid)**.

2. Have an issue with the *Solid spec* specifically? **Open an issue on [solid/solid](https://github.com/solid) anyway.** And then, as a result of discussion, if it's agreed that it is actually a Spec issue, it will be moved to `solid-spec`.

3. The individual [solid/solid](https://github.com/solid) issues can coordinate and track component/dependent issues on the various affected Solid servers, apps, and so on.

To Do:

- [ ] Go through the existing `solid-spec` Issues, move them to `solid` Issues.
- [ ] Document this workflow on [solid/solid](https://github.com/solid) README
- [ ] Document this workflow on [solid/solid-spec](https://github.com/solid-spec) README
